# Generated by Django 5.2.17 on 2026-09-06 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__regex', '^[0-9]+$')), name='phone_number_digits_only'),
        ),
    ]
