# Generated by Django 5.2.17 on 2026-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerprofile_phone_number_digits_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='theme',
            field=models.CharField(default='default', max_length=15),
        ),
    ]
