# Generated by Django 5.2.17 on 2026-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customerprofile_id_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='theme',
            field=models.CharField(default='default', max_length=15, null=True),
        ),
    ]
