# Generated by Django 5.2.17 on 2026-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='language',
            field=models.CharField(default='en', max_length=2, null=True),
        ),
    ]
