# Generated by Django 5.2.17 on 2026-09-06 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerprofile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerprofile',
            name='phone_number_digits_only',
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__regex', '^\\+?[0-9]+$')), name='phone_number_digits_only'),
        ),
    ]
