# Generated by Django 5.2.17 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customerprofile_phone_number_digits_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='theme',
            field=models.CharField(blank=True, default='default', max_length=15, null=True),
        ),
    ]
