# Generated by Django 5.2.17 on 2026-09-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customerprofile_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user',
            new_name='customer',
        ),
    ]
