# Generated by Django 5.2.17 on 2026-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
