# Generated by Django 5.2.17 on 2026-09-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customerprofile_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer',
            new_name='user',
        ),
    ]
