# Generated by Django 5.2.17 on 2026-09-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_rename_customer_customerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
    ]
