# Generated by Django 5.2.17 on 2026-09-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=15)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
