# Generated by Django 5.2.17 on 2026-09-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_id',
            new_name='user',
        ),
    ]
