# Generated by Django 5.2.17 on 2026-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_rename_user_id_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='NEW', max_length=15),
        ),
    ]
