# Generated by Django 5.2.17 on 2026-09-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_rename_user_customerprofile_customer'),
        ('requests', '0004_rename_description_request_problem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_request', to='customers.customerprofile'),
        ),
    ]
