# Generated by Django 5.2.17 on 2026-09-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='customer',
        ),
    ]
