# Generated by Django 5.2.17 on 2026-09-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_rename_status_request_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='statu',
            new_name='status',
        ),
    ]
