# Generated by Django 5.2.17 on 2026-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_rename_statu_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerificationn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField()),
            ],
        ),
    ]
