# Generated by Django 5.2.17 on 2026-09-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_otpverificationn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerificationn',
        ),
    ]
