# Generated by Django 5.2.17 on 2026-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_delete_otpverificationn'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
