# Generated by Django 5.2.17 on 2026-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_delete_otpverificationn'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
